# Generated by Django 5.2.15 on 2026-06-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streamer", "0002_animeroom_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="animeuser",
            name="user_icon",
            field=models.CharField(default="FaRegUser", max_length=64),
        ),
    ]
