# Generated by Django 5.2.15 on 2026-06-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streamer", "0003_animeuser_user_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReactionStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[
                            ("C", "cry"),
                            ("MF", "middle_finger"),
                            ("S", "smile"),
                            ("TU", "thumbs_up"),
                            ("F", "favorite"),
                        ],
                        max_length=3,
                    ),
                ),
                ("count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["date"], name="streamer_re_date_8a952e_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "reaction_type"),
                        name="uniq_reactionstat_date_type",
                    )
                ],
            },
        ),
    ]
