# Generated by Django 5.2.15 on 2026-07-02 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streamer", "0004_reactionstat"),
    ]

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="setting",
                        serialize=False,
                        to="streamer.animeroom",
                    ),
                ),
                ("one_way", models.BooleanField(default=False)),
                ("owner_leave_delete", models.BooleanField(default=False)),
                ("disable_reaction", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
