# Generated by Django 5.2.15 on 2026-07-05 10:24

import django.db.models.deletion
import streamer.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streamer", "0005_setting"),
    ]

    operations = [
        migrations.CreateModel(
            name="DmmRoom",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        verbose_name="deleted date",
                    ),
                ),
                (
                    "room_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("num_people", models.PositiveSmallIntegerField(default=1)),
                ("sum_people", models.PositiveSmallIntegerField(default=1)),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("part_id", models.CharField(max_length=128)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DmmReactionStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[
                            ("C", "cry"),
                            ("MF", "middle_finger"),
                            ("S", "smile"),
                            ("TU", "thumbs_up"),
                            ("F", "favorite"),
                        ],
                        max_length=3,
                    ),
                ),
                ("count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["date"], name="streamer_dm_date_3b44d1_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "reaction_type"),
                        name="uniq_dmm_reactionstat_date_type",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DmmSetting",
            fields=[
                ("one_way", models.BooleanField(default=False)),
                ("owner_leave_delete", models.BooleanField(default=False)),
                ("disable_reaction", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="setting",
                        serialize=False,
                        to="streamer.dmmroom",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DmmReaction",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        verbose_name="deleted date",
                    ),
                ),
                (
                    "reaction_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[
                            ("C", "cry"),
                            ("MF", "middle_finger"),
                            ("S", "smile"),
                            ("TU", "thumbs_up"),
                            ("F", "favorite"),
                        ],
                        max_length=3,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="streamer.dmmroom",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DmmRoomHistory",
            fields=[
                (
                    "user_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("type", models.CharField(max_length=20)),
                (
                    "room_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="streamer.dmmroom",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DmmUser",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        verbose_name="deleted date",
                    ),
                ),
                (
                    "user_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_name",
                    streamer.fields.EncryptedCharField(default="user", max_length=20),
                ),
                ("user_icon", models.CharField(default="FaRegUser", max_length=64)),
                ("is_host", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "room_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inroom",
                        to="streamer.dmmroom",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
