x-env_file: &env_file ./.env.global

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  nginx:
    container_name: nginx
    image: nginx:1.27
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/:/etc/nginx/"
      - "./Django/static:/static"
      - "./nginx/.well-known:/.well-known"
    depends_on:
      - django
    env_file: *env_file
  django:
    container_name: django
    build:
      context: Django
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./Django/:/usr/src/app/
      - ./Django/.env.django:/env_files/.env.django
      - .env.global:/env_files/.env.global
    command: "sh entrypoint.sh"
    env_file:
      - ./Django/.env.django
      - *env_file
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - "./Postgres/data:/var/lib/postgresql/data"
    env_file:
      - ./Postgres/.env.postgres
      - *env_file
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
  adminer:
    image: adminer:4
    container_name: adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
  redis:
    image: redis:7.4
    container_name: redis
    ports:
      - 6379:6379
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.1.0
    volumes:
      - ./prometheus/:/etc/prometheus/
    #      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    depends_on:
      - cadvisor
      - django

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    deploy:
      mode: global

  cadvisor:
    container_name: cadvisor
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 5050:8080
    deploy:
      mode: global

  grafana:
    container_name: grafana
    image: grafana/grafana
    user: "472"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/.env.grafana
