/**
 * リアクション用の静的アイコン（react-icons）解決マップ。
 *
 * {@link src/components/userIcons.ts} の `USER_ICONS` と同じ方針で、カタログ
 * （デフォルト＋エクストラ）が使う react-icons だけを import して 1 つの map に
 * 束ねる。これによりバンドルは必要な subset だけを取り込む。`reactIcon` キー
 * （例 `"FaThumbsUp"`）から map ルックアップで解決する。
 */

import type { IconType } from "react-icons/lib";
import {
  FaAppleWhole,
  FaBacon,
  FaBaseball,
  FaBasketball,
  FaBeerMugEmpty,
  FaBell,
  FaBolt,
  FaBomb,
  FaBone,
  FaBowlingBall,
  FaBrain,
  FaBreadSlice,
  FaBullseye,
  FaBurger,
  FaCakeCandles,
  FaCamera,
  FaCanadianMapleLeaf,
  FaCarrot,
  FaCat,
  FaCheese,
  FaCircleCheck,
  FaCircleXmark,
  FaClapperboard,
  FaCloud,
  FaComment,
  FaCookie,
  FaCow,
  FaCrown,
  FaDice,
  FaDog,
  FaDragon,
  FaDroplet,
  FaDrum,
  FaDrumstickBite,
  FaExclamation,
  FaEye,
  FaFaceAngry,
  FaFaceGrin,
  FaFaceGrinHearts,
  FaFaceGrinSquintTears,
  FaFaceGrinStars,
  FaFaceGrinTears,
  FaFaceGrinTongue,
  FaFaceGrinWink,
  FaFaceKissWinkHeart,
  FaFaceMeh,
  FaFaceRollingEyes,
  FaFaceSadCry,
  FaFaceSmileBeam,
  FaFaceSurprise,
  FaFire,
  FaFish,
  FaFlagCheckered,
  FaFrog,
  FaFutbol,
  FaGem,
  FaGhost,
  FaGift,
  FaGuitar,
  FaHand,
  FaHandFist,
  FaHandMiddleFinger,
  FaHandPeace,
  FaHandPointDown,
  FaHandPointLeft,
  FaHandPointRight,
  FaHandSpock,
  FaHandsClapping,
  FaHandsPraying,
  FaHandshake,
  FaHeart,
  FaHeartCrack,
  FaHorse,
  FaHotdog,
  FaIceCream,
  FaLeaf,
  FaLemon,
  FaLightbulb,
  FaLock,
  FaMagnifyingGlass,
  FaMoon,
  FaMosquito,
  FaMusic,
  FaOtter,
  FaPaw,
  FaPizzaSlice,
  FaPoo,
  FaQuestion,
  FaRocket,
  FaSailboat,
  FaScissors,
  FaSeedling,
  FaSkull,
  FaSnowflake,
  FaSpider,
  FaStar,
  FaSun,
  FaTableTennisPaddleBall,
  FaThumbsDown,
  FaThumbsUp,
  FaTree,
  FaTrophy,
  FaWineGlass,
  FaWorm,
} from "react-icons/fa6";
import {
  GiSharkFin,
} from "react-icons/gi";

/** 未知キーのフォールバック（必ず import 済みのアイコンを指す）。 */
const FALLBACK_REACTION_ICON = "FaQuestion";

/** react-icons キー → コンポーネント。 */
export const REACTION_ICONS: Record<string, IconType> = {
  FaAppleWhole,
  FaBacon,
  FaBaseball,
  FaBasketball,
  FaBeerMugEmpty,
  FaBell,
  FaBolt,
  FaBomb,
  FaBone,
  FaBowlingBall,
  FaBrain,
  FaBreadSlice,
  FaBullseye,
  FaBurger,
  FaCakeCandles,
  FaCamera,
  FaCanadianMapleLeaf,
  FaCarrot,
  FaCat,
  FaCheese,
  FaCircleCheck,
  FaCircleXmark,
  FaClapperboard,
  FaCloud,
  FaComment,
  FaCookie,
  FaCow,
  FaCrown,
  FaDice,
  FaDog,
  FaDragon,
  FaDroplet,
  FaDrum,
  FaDrumstickBite,
  FaExclamation,
  FaEye,
  FaFaceAngry,
  FaFaceGrin,
  FaFaceGrinHearts,
  FaFaceGrinSquintTears,
  FaFaceGrinStars,
  FaFaceGrinTears,
  FaFaceGrinTongue,
  FaFaceGrinWink,
  FaFaceKissWinkHeart,
  FaFaceMeh,
  FaFaceRollingEyes,
  FaFaceSadCry,
  FaFaceSmileBeam,
  FaFaceSurprise,
  FaFire,
  FaFish,
  FaFlagCheckered,
  FaFrog,
  FaFutbol,
  FaGem,
  FaGhost,
  FaGift,
  FaGuitar,
  FaHand,
  FaHandFist,
  FaHandMiddleFinger,
  FaHandPeace,
  FaHandPointDown,
  FaHandPointLeft,
  FaHandPointRight,
  FaHandSpock,
  FaHandsClapping,
  FaHandsPraying,
  FaHandshake,
  FaHeart,
  FaHeartCrack,
  FaHorse,
  FaHotdog,
  FaIceCream,
  FaLeaf,
  FaLemon,
  FaLightbulb,
  FaLock,
  FaMagnifyingGlass,
  FaMoon,
  FaMosquito,
  FaMusic,
  FaOtter,
  FaPaw,
  FaPizzaSlice,
  FaPoo,
  FaQuestion,
  FaRocket,
  FaSailboat,
  FaScissors,
  FaSeedling,
  FaSkull,
  FaSnowflake,
  FaSpider,
  FaStar,
  FaSun,
  FaTableTennisPaddleBall,
  FaThumbsDown,
  FaThumbsUp,
  FaTree,
  FaTrophy,
  FaWineGlass,
  FaWorm,
  GiSharkFin,
};

/**
 * 保存済みの react-icons キーからリアクションアイコンを描画する。未知/未指定は
 * フォールバックする。`UserAvatar` と同様、レンダー中の動的コンポーネント生成を
 * 避けるため map ルックアップ（安定参照）で解決する。
 */
export function ReactionIcon({
  iconKey,
  className,
}: {
  iconKey?: string;
  className?: string;
}): React.JSX.Element {
  const Icon =
    (iconKey && REACTION_ICONS[iconKey]) ||
    REACTION_ICONS[FALLBACK_REACTION_ICON];
  return <Icon className={className} aria-hidden />;
}
