"""
Django settings for d_party project.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path

from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ["DEBUG"] == "1"

ALLOWED_HOSTS = [os.environ["MY_DOMAIN"], "www." + os.environ["MY_DOMAIN"], "django"]
if DEBUG:
    # 開発・テスト用の明示的な許可ホスト。``["*"]`` だと誤って DEBUG=1 のまま本番に
    # 出たとき Host ヘッダインジェクションを許してしまうため、ワイルドカードは使わない。
    ALLOWED_HOSTS += ["localhost", "127.0.0.1", "[::1]", "testserver"]
CSRF_TRUSTED_ORIGINS = [
    "https://*." + os.environ["MY_DOMAIN"],
    "https://*.127.0.0.1",
    "wss://*." + os.environ["MY_DOMAIN"],
    "wss://*.127.0.0.1",
]


# Application definition

INSTALLED_APPS = [
    "daphne",
    # django-unfold: 管理画面テーマ。django.contrib.admin より前に置く必要がある。
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",
    "channels",
    "rest_framework",
    "axes",
    "django_prometheus",
    "streamer",
    "api",
]

AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesBackend",
    "django.contrib.auth.backends.ModelBackend",
]

MIDDLEWARE = [
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "axes.middleware.AxesMiddleware",
    "django_prometheus.middleware.PrometheusAfterMiddleware",
]

ROOT_URLCONF = "d_party.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # プロジェクト直下の templates/ を最優先（filesystem loader は app loader より
        # 先に評価される）。unfold の admin/index.html をダッシュボードで上書きする。
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# redis
REDIS_HOST = os.environ.get("REDIS_HOST", "redis")
REDIS_PORT = int(os.environ.get("REDIS_PORT", "6379"))
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.pubsub.RedisPubSubChannelLayer",
        "CONFIG": {"hosts": [f"redis://{REDIS_HOST}:{REDIS_PORT}/0"]},
    }
}

# 統計 API のレスポンスキャッシュ。channel layer の DB 0 と分けて DB 1 を使う。
# 毎リクエストでの DB 集計を避け、TTL（STATS_CACHE_SECONDS）失効で自然反映する。
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": f"redis://{REDIS_HOST}:{REDIS_PORT}/1",
        "KEY_PREFIX": "dparty",
    }
}

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.environ["DATABASE_ENGINE"],
        "NAME": os.environ["POSTGRES_DB"],
        "USER": os.environ["DATABASE_USER"],
        "PASSWORD": os.environ["POSTGRES_PASSWORD"],
        "HOST": os.environ["DATABASE_HOST"],
        "PORT": os.environ["DATABASE_PORT"],
        "TEST": {
            "NAME": "test_db",
            "MIRROR": "default",
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = os.environ["LANGUAGE_CODE"]

TIME_ZONE = os.environ["TIME_ZONE"]

USE_I18N = True

USE_TZ = True

# django-unfold（管理画面テーマ）。旧 django-jazzmin から移行。
# ブランディング・サイドバー・ダッシュボードを設定する。ダーク/ライトは
# unfold が自動対応する（旧 jazzmin の darkly 固定で起きたヘッダー黒つぶれを解消）。
UNFOLD = {
    "SITE_TITLE": "d-party",
    "SITE_HEADER": "d-party",
    "SITE_SUBHEADER": _("同時視聴 管理コンソール"),
    # ロゴ未表示時のフォールバックに使う Material Symbols アイコン名。
    "SITE_SYMBOL": "smart_display",
    "SITE_LOGO": {
        "light": lambda request: static("branding/dp-mini.png"),
        "dark": lambda request: static("branding/dp-mini.png"),
    },
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "SHOW_BACK_BUTTON": False,
    # 環境バッジ（DEBUG に応じて Development/Production を表示）。
    "ENVIRONMENT": "d_party.dashboard.environment_callback",
    # トップページのダッシュボード（KPI カード）を差し込むコールバック。
    "DASHBOARD_CALLBACK": "d_party.dashboard.dashboard_callback",
    "COLORS": {
        # d-party のブランドに合わせた紫系のプライマリカラー。
        "primary": {
            "50": "oklch(97.7% .014 308.299)",
            "100": "oklch(94.6% .033 307.174)",
            "200": "oklch(90.2% .063 306.703)",
            "300": "oklch(82.7% .119 306.383)",
            "400": "oklch(71.4% .203 305.504)",
            "500": "oklch(62.7% .265 303.9)",
            "600": "oklch(55.8% .288 302.321)",
            "700": "oklch(49.6% .265 301.924)",
            "800": "oklch(43.8% .218 303.724)",
            "900": "oklch(38.1% .176 304.987)",
            "950": "oklch(29.1% .149 302.717)",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": _("ナビゲーション"),
                "separator": True,
                "items": [
                    {
                        "title": _("ダッシュボード"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },
            {
                "title": _("同時視聴"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("ルーム"),
                        "icon": "meeting_room",
                        "link": reverse_lazy("admin:streamer_animeroom_changelist"),
                    },
                    {
                        "title": _("ユーザー"),
                        "icon": "group",
                        "link": reverse_lazy("admin:streamer_animeuser_changelist"),
                    },
                    {
                        "title": _("リアクション"),
                        "icon": "favorite",
                        "link": reverse_lazy("admin:streamer_animereaction_changelist"),
                    },
                    {
                        "title": _("ルーム詳細設定"),
                        "icon": "tune",
                        "link": reverse_lazy("admin:streamer_setting_changelist"),
                    },
                ],
            },
            {
                "title": _("アカウント"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("ユーザー（認証）"),
                        "icon": "person",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": _("グループ"),
                        "icon": "shield_person",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
            {
                "title": _("外部リンク"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("統計チャート"),
                        "icon": "bar_chart",
                        "link": "/stats",
                    },
                    {
                        "title": _("Grafana"),
                        "icon": "monitoring",
                        "link": "/grafana/",
                    },
                ],
            },
        ],
    },
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static/")
# 公開ページ（LP・使い方・統計など）は frontend サブモジュールへ移行済みのため、
# Django 側のアプリ static は持たない。管理画面（Jazzmin）のロゴ等のブランディング
# 素材だけをここから配信する。
STATICFILES_DIRS = [os.path.join(BASE_DIR, "assets")]

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Channels
ASGI_APPLICATION = "d_party.asgi.application"

# axes
AXES_FAILURE_LIMIT = 10
AXES_COOLOFF_TIME = 6
# Preserve the previous "lock by username only" behaviour
# (replaces the deprecated AXES_ONLY_USER_FAILURES).
AXES_LOCKOUT_PARAMETERS = ["username"]
AXES_RESET_ON_SUCCESS = True

if DEBUG:
    AXES_ENABLED = False

# django-extensions
RUNSERVERPLUS_SERVER_ADDRESS_PORT = "0.0.0.0:8000"
