/**
 * WebSocket message protocol shared with the backend.
 *
 * These types are the TypeScript mirror of the backend's
 * `streamer/format.py` (outgoing) and the consumer actions (incoming).
 * Keep them in lock-step with the backend — the wire format is a public
 * contract. (Not generated by orval because OpenAPI cannot express the
 * WebSocket protocol.)
 */

export interface User {
  user_id: string;
  user_name: string;
  /**
   * 表示アイコン（react-icons / Font Awesome 6 のキー文字列）。
   * 旧バックエンド互換のため任意（未指定なら既定アイコンにフォールバック）。
   */
  user_icon?: string;
  /**
   * ルームのホスト（オーナー）かどうか。`user_list` で配信される。
   * 旧バックエンド互換のため任意（未指定なら非ホスト扱い）。
   */
  is_host?: boolean;
}

/** Player state as reported by the extension (sent to the server). */
export interface PlayerOption {
  time: number;
  src: string | null;
  paused: boolean;
  rate: number;
  part_id: string;
}

/**
 * Player state as received from the server. The backend stringifies
 * `paused`/`rate` (pydantic), e.g. `paused` is `"True"` / `"False"`.
 */
export interface SyncOption {
  time: number;
  src: string | null;
  paused: string;
  rate: string;
  part_id: string;
}

// ---------------------------------------------------------------------------
// Outgoing messages (client -> server). Each carries a `request_id`.
// ---------------------------------------------------------------------------

export interface CreateRoomMessage {
  action: "create";
  user_name: string;
  /** 表示アイコン（react-icons / FA6 のキー）。バックエンドは未指定でも受理する。 */
  user_icon: string;
  part_id: string;
  /**
   * 視聴中アニメのタイトル（ページ DOM から取得）。OGP 表示用にルーム作成時に
   * 一度だけ送る。バックエンドは未指定でも受理する（旧バージョン互換）。
   */
  title: string;
  request_id: number;
}

export interface JoinRoomMessage {
  action: "join";
  user_name: string;
  /** 表示アイコン（react-icons / FA6 のキー）。バックエンドは未指定でも受理する。 */
  user_icon: string;
  room_id: string;
  request_id: number;
}

export interface VideoOperationMessage {
  action: "video_operation";
  user_id: string;
  operation: string;
  option: PlayerOption;
  request_id: number;
}

export interface SyncRequestMessage {
  action: "sync_request";
  request_id: number;
}

export interface SyncResponseMessage {
  action: "sync_response";
  to_user: User;
  option: PlayerOption;
  request_id: number;
}

export interface OperationNotificationMessage {
  action: "operation_notification";
  operation: string;
  user_name: string;
  request_id: number;
}

export interface LeaveMessage {
  action: "leave";
  user_name: string;
  request_id: number;
}

export interface UserListRequestMessage {
  action: "user_list";
  request_id: number;
}

/** ホスト（オーナー）がルームを削除する要求。ホスト以外が送っても無視される。 */
export interface DeleteRoomMessage {
  action: "delete_room";
  request_id: number;
}

export interface ReactionMessage {
  action: "reaction";
  /** デフォルト名（`fav` 等）または エクストラ id（Noto コードポイント）。 */
  reaction_type: string;
  request_id: number;
}

/**
 * ルーム詳細設定の更新要求（オーナー限定。ホスト以外が送っても無視される）。
 * ルーム作成直後の初期設定・入室後の変更の両方で使う。旧バックエンドはこの
 * action を知らず無視するため後方互換（設定が効かないだけで通常動作は維持）。
 */
export interface UpdateSettingMessage {
  action: "update_setting";
  one_way: boolean;
  owner_leave_delete: boolean;
  disable_reaction: boolean;
  request_id: number;
}

export type OutgoingMessage =
  | CreateRoomMessage
  | JoinRoomMessage
  | VideoOperationMessage
  | SyncRequestMessage
  | SyncResponseMessage
  | OperationNotificationMessage
  | LeaveMessage
  | UserListRequestMessage
  | DeleteRoomMessage
  | ReactionMessage
  | UpdateSettingMessage;

// ---------------------------------------------------------------------------
// Incoming messages (server -> client).
// ---------------------------------------------------------------------------

export interface VideoOperationEvent {
  action: "video_operation";
  room_id: string;
  operation: string;
  user: User;
  option: SyncOption;
}

export interface CreateEvent {
  action: "create";
  room_id: string;
  user: User;
}

export interface JoinEvent {
  action: "join";
  room_id: string;
  user: User;
}

export interface ServerMessageEvent {
  action: "server_message";
  /** Present for control messages such as "host_change". */
  message_type?: string;
  /** Present for the join-failure message ("failed_join"). */
  message?: string;
}

export interface UserAddEvent {
  action: "user_add";
  user: User;
}

export interface UserListEvent {
  action: "user_list";
  user_list: User[];
}

export interface LeaveEvent {
  action: "leave";
  user: User;
}

export interface SyncRequestEvent {
  action: "sync_request";
  user: User;
}

export interface SyncResponseEvent {
  action: "sync_response";
  option: SyncOption;
}

export interface OperationNotificationEvent {
  action: "operation_notification";
  operation: string;
  user: User;
}

export interface ReactionEvent {
  action: "reaction";
  /** デフォルト名（`fav` 等）または エクストラ id（Noto コードポイント）。 */
  reaction_type: string;
  /** 送信者（バッジ表示の「ユーザー名 : リアクション」用）。旧バックエンド互換で任意。 */
  user?: User;
}

/**
 * ルーム詳細設定の通知（サーバ push）。ルーム作成/参加時と、オーナーによる更新時に
 * ルーム全員へ配信される。旧バックエンドは送らないため、未受信なら既定値（false）扱い。
 */
export interface RoomSettingEvent {
  action: "room_setting";
  one_way?: boolean;
  owner_leave_delete?: boolean;
  disable_reaction?: boolean;
}

export type IncomingMessage =
  | VideoOperationEvent
  | CreateEvent
  | JoinEvent
  | ServerMessageEvent
  | UserAddEvent
  | UserListEvent
  | LeaveEvent
  | SyncRequestEvent
  | SyncResponseEvent
  | OperationNotificationEvent
  | ReactionEvent
  | RoomSettingEvent;
