/**
 * WebSocket message protocol shared with the backend.
 *
 * These types are the TypeScript mirror of the backend's
 * `streamer/format.py` (outgoing) and the consumer actions (incoming).
 * Keep them in lock-step with the backend — the wire format is a public
 * contract. (Not generated by orval because OpenAPI cannot express the
 * WebSocket protocol.)
 */

import type { ReactionType } from "./reactions";

export interface User {
  user_id: string;
  user_name: string;
}

/** Player state as reported by the extension (sent to the server). */
export interface PlayerOption {
  time: number;
  src: string | null;
  paused: boolean;
  rate: number;
  part_id: string;
}

/**
 * Player state as received from the server. The backend stringifies
 * `paused`/`rate` (pydantic), e.g. `paused` is `"True"` / `"False"`.
 */
export interface SyncOption {
  time: number;
  src: string | null;
  paused: string;
  rate: string;
  part_id: string;
}

// ---------------------------------------------------------------------------
// Outgoing messages (client -> server). Each carries a `request_id`.
// ---------------------------------------------------------------------------

export interface CreateRoomMessage {
  action: "create";
  user_name: string;
  part_id: string;
  /**
   * 視聴中アニメのタイトル（ページ DOM から取得）。OGP 表示用にルーム作成時に
   * 一度だけ送る。バックエンドは未指定でも受理する（旧バージョン互換）。
   */
  title: string;
  request_id: number;
}

export interface JoinRoomMessage {
  action: "join";
  user_name: string;
  room_id: string;
  request_id: number;
}

export interface VideoOperationMessage {
  action: "video_operation";
  user_id: string;
  operation: string;
  option: PlayerOption;
  request_id: number;
}

export interface SyncRequestMessage {
  action: "sync_request";
  request_id: number;
}

export interface SyncResponseMessage {
  action: "sync_response";
  to_user: User;
  option: PlayerOption;
  request_id: number;
}

export interface OperationNotificationMessage {
  action: "operation_notification";
  operation: string;
  user_name: string;
  request_id: number;
}

export interface LeaveMessage {
  action: "leave";
  user_name: string;
  request_id: number;
}

export interface UserListRequestMessage {
  action: "user_list";
  request_id: number;
}

export interface ReactionMessage {
  action: "reaction";
  reaction_type: ReactionType;
  request_id: number;
}

export type OutgoingMessage =
  | CreateRoomMessage
  | JoinRoomMessage
  | VideoOperationMessage
  | SyncRequestMessage
  | SyncResponseMessage
  | OperationNotificationMessage
  | LeaveMessage
  | UserListRequestMessage
  | ReactionMessage;

// ---------------------------------------------------------------------------
// Incoming messages (server -> client).
// ---------------------------------------------------------------------------

export interface VideoOperationEvent {
  action: "video_operation";
  room_id: string;
  operation: string;
  user: User;
  option: SyncOption;
}

export interface CreateEvent {
  action: "create";
  room_id: string;
  user: User;
}

export interface JoinEvent {
  action: "join";
  room_id: string;
  user: User;
}

export interface ServerMessageEvent {
  action: "server_message";
  /** Present for control messages such as "host_change". */
  message_type?: string;
  /** Present for the join-failure message ("failed_join"). */
  message?: string;
}

export interface UserAddEvent {
  action: "user_add";
  user: User;
}

export interface UserListEvent {
  action: "user_list";
  user_list: User[];
}

export interface LeaveEvent {
  action: "leave";
  user: User;
}

export interface SyncRequestEvent {
  action: "sync_request";
  user: User;
}

export interface SyncResponseEvent {
  action: "sync_response";
  option: SyncOption;
}

export interface OperationNotificationEvent {
  action: "operation_notification";
  operation: string;
  user: User;
}

export interface ReactionEvent {
  action: "reaction";
  reaction_type: ReactionType;
}

export type IncomingMessage =
  | VideoOperationEvent
  | CreateEvent
  | JoinEvent
  | ServerMessageEvent
  | UserAddEvent
  | UserListEvent
  | LeaveEvent
  | SyncRequestEvent
  | SyncResponseEvent
  | OperationNotificationEvent
  | ReactionEvent;
